name:                LamE
version:             1.1.0
github:              "zyxw121/LamE"
license:             BSD3
author:              "Daniel Mroz"
maintainer:          "daniel.mroz@univ.ox.ac.uk"
copyright:           "2018 Daniel Mroz"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/zyxw121/LamE#readme>

dependencies:
- base >= 4.7 && < 5
- transformers

library:
  source-dirs: src
  exposed-modules: 
  - Core 
  - Syntax
  - Parser
  - Eval
  - Terms
  - Env
  other-modules:
  dependencies:
  - parsec 

executables:
  LamEC:
    main:                Main.hs
    source-dirs:         LamEC
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LamE

  LamER:
    main:                Main.hs
    source-dirs:         LamER
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LamE

tests:
  LamE-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LamE
    - hspec
    - QuickCheck
    - parsec
